// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAmIy5gQqexQ3WNb6pPGd9YifNSGknDw',
    appId: '1:325752834360:web:85c12da6eeec1c8b5719cd',
    messagingSenderId: '325752834360',
    projectId: 'torneos-futbol-app',
    authDomain: 'torneos-futbol-app.firebaseapp.com',
    storageBucket: 'torneos-futbol-app.firebasestorage.app',
    measurementId: 'G-ZSMVX6SD5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Lxd3ecVL8zin4hs0cPM4ZVlAIstCj48',
    appId: '1:325752834360:android:3d5b5bd80cf09f075719cd',
    messagingSenderId: '325752834360',
    projectId: 'torneos-futbol-app',
    storageBucket: 'torneos-futbol-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhV7gZSN3LLEoKH8Fo-FkzYC7zCV8uEQ',
    appId: '1:325752834360:ios:97c6fb300d8f45425719cd',
    messagingSenderId: '325752834360',
    projectId: 'torneos-futbol-app',
    storageBucket: 'torneos-futbol-app.firebasestorage.app',
    iosBundleId: 'com.example.torneosFutbol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhV7gZSN3LLEoKH8Fo-FkzYC7zCV8uEQ',
    appId: '1:325752834360:ios:97c6fb300d8f45425719cd',
    messagingSenderId: '325752834360',
    projectId: 'torneos-futbol-app',
    storageBucket: 'torneos-futbol-app.firebasestorage.app',
    iosBundleId: 'com.example.torneosFutbol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxAmIy5gQqexQ3WNb6pPGd9YifNSGknDw',
    appId: '1:325752834360:web:6a88604181834ce05719cd',
    messagingSenderId: '325752834360',
    projectId: 'torneos-futbol-app',
    authDomain: 'torneos-futbol-app.firebaseapp.com',
    storageBucket: 'torneos-futbol-app.firebasestorage.app',
    measurementId: 'G-LBN1YQ5M7S',
  );
}
